In [1]:
import numpy as np
import scipy as sp
import pandas as pd
import  matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
import sklearn as sk
import statsmodels.api as sm
plt.rc("font", family="Malgun Gothic")
mpl.rcParams['axes.unicode_minus'] = False


In [2]:
X1 = np.random.normal(size=100)
X2 = np.random.normal(size=100)
X = X1 + X2

In [3]:
np.var(X), np.var(X1) + np.var(X2)

(1.939063883339218, 1.6706016764153935)

In [4]:
X1 = np.random.rand(100)
np.var(X1)

0.07928180154581738

In [5]:
X_mean = []
X_var = []
for i in range(50):
    a = (np.random.rand(100))
    X_mean.append(np.mean(a))
    X_var.append(np.var(a))
np.var(X_mean), X_var[0]

(0.0008109961935556806, 0.08685433355176371)

In [6]:
omega = [1,2,3]
x_bar1 = []
for i in range(1000):
    x_bar1.append(np.mean(np.random.randint(1,4,5)))

x_bar2 = []
for i in range(10):
    x_bar2.append(np.mean(np.random.randint(1,4,50000)))   

np.mean(x_bar1), np.mean(x_bar2)

(1.986, 1.9986120000000003)

In [10]:
from sklearn.datasets import load_iris
from scipy import stats
X = load_iris().data
X1 = X[:, 0]
X2 = X[:, 1]
X3 = X[:, 2]
X4 = X[:, 3]

In [14]:
stats.pearsonr(X1, X2)[0], stats.pearsonr(X3, X4)[0], stats.pearsonr(X2, X4)[0]

(-0.11756978413300204, 0.962865431402796, -0.3661259325364391)

In [25]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
stats.pearsonr(a, b)

(-0.24124014758753512, 0.5019408622873808)

In [38]:
pick =  np.random.randint(0,10,3)
a_bar = [a[i] for i in pick]
b_bar = [b[i] for i in pick]
stats.pearsonr(a_bar, b_bar)

(-1.0, 0.0)

In [55]:
a = np.random.randint(0,10,10000)
b = np.random.randint(0,10,10000)
stats.pearsonr(a, b)

(0.020110493642031976, 0.044325317021311914)

In [61]:
pick =  np.random.randint(0,10,100000)
a_bar = [a[i] for i in pick]
b_bar = [b[i] for i in pick]
stats.pearsonr(a_bar, b_bar)

(-0.3695709805385222, 0.0)

In [67]:
X1.mean(), X2.mean(), X3.mean(), X4.mean()

(5.843333333333334, 3.0573333333333337, 3.7580000000000005, 1.1993333333333336)

In [75]:
np.vstack((np.array([[1,0,0]]), np.array([[1,1,0]])))

array([[1, 0, 0],
       [1, 1, 0]])

In [79]:
X_bar = np.vstack((X1-X1.mean(), X2-X2.mean(), X3-X3.mean(), X4-X4.mean()))

In [82]:
1 / 150 * X_bar @ X_bar.T

array([[ 0.68112222, -0.04215111,  1.26582   ,  0.51282889],
       [-0.04215111,  0.18871289, -0.32745867, -0.12082844],
       [ 1.26582   , -0.32745867,  3.09550267,  1.286972  ],
       [ 0.51282889, -0.12082844,  1.286972  ,  0.57713289]])

In [83]:
np.cov(X.T, ddof=0)

array([[ 0.68112222, -0.04215111,  1.26582   ,  0.51282889],
       [-0.04215111,  0.18871289, -0.32745867, -0.12082844],
       [ 1.26582   , -0.32745867,  3.09550267,  1.286972  ],
       [ 0.51282889, -0.12082844,  1.286972  ,  0.57713289]])